shellscape/webpack-plugin-serve

- lib/client/hmr.js
When destructuring `module.hot`, when `hmr:false`, `module.hot` does not exist, so it would throw an error. 
Fix #46
> fix: destructuring of undefined or null variables. fixes #46

- lib/client/ClientSocket.js
Fixes #59. When implementing the `ClientSocket` class for reconnectivity, we neglected to add a `close` method to passthrough to the underlying socket. This generated a harmless error in both the browser console and the system console/terminal.
> fix: add close passthrough method to ClientSocket #59

- lib/errors.js
- lib/hmr-plugin.js
- test/fixtures/simple/index.html
This PR introduces a breaking change, though it's not likely to impact our modest user base at this time: if a user has introduced a `HotModuleReplacementPlugin` instance to the configuration's `plugins` before the `WebpackPluginServe` instance, this plugin with throw an exception.
Previously, we were trying to be cute and work around that by modifying webpack internals. That was a noble goal initially, but with the introduction of MultiCompiler support, the complexity of the code required to do so increased significantly, and to make that work with #60 will add even more. All of that points to increased fragility of our code to work around things in webpack. Keeping that complexity will ultimately make upgrades harder for us moving forward.
Throwing an error requesting …
> fix: use static hmr filenames

- recipes/open-custom-uri.md
Adds a recipe for opening a custom uri, rather than the uri of the root of the application. Resolves #64
> docs: add custom open uri recipe

- package.json
Closes #73 - adds support for node 11 to align with other _evergreen_ repos.
> feat: Add support for node 11 in 'engines'

- .github/FAQ.md
There's a slight error in the documentation. The FAQs incorrectly state how to serve content from multiple directories. I believe the property in the options is "static", not "serve".
> Fix minor error in faqs - Serve from multiple directories

- lib/client/overlays/progress-minimal.js
- lib/client/overlays/progress.js
- lib/client/overlays/status.js
As #81 suggested and we also had discussed before on the approach we should use to set those overlays on top of every possible scenario, be aware that, i preferred to decrease -2 on the max `z-index` allowed as a cautions action, to not walk on the edge every time, so we have a margin of error.
> fix: z-index on overlays set to max allowed. fix #81

- README.md
- index.d.ts
- lib/middleware.js
Resolves #80. Adds the ability to pass options for `koa-static` via the `builtins.static` middleware.
> feat: static middleware options

- package.json
Add support for node 10.15.0 and above in 'engines', since 10.15 fixes #47 by way of https://github.com/nodejs/node/commit/1aea1e3634de7331f670f0594c023ca7c64a759f
> chore(meta): Add support for node 10.15.0 and above in 'engines'

- README.md
- client.js
- lib/client/client.js
- lib/client/log.js
Fixes #88. Adds a `client.silent` option to silence console output in the browser/client.
> feat: add client.silent option

- README.md
- lib/middleware.js
Fixes #94. When using Firefox with the `historyFallback` option (`connect-history-api-fallback`), the `/wps` WebSocket path is incorrectly given an `Accept` header, which makes the middleware think it's a directory index. The added middleware strips that header in that event, preventing the error, only when the `historyFallback` option is used.
> fix: strip accept header when using history-api-fallback

- recipes/react-ssr/.eslintrc
- recipes/react-ssr/README.md
- recipes/react-ssr/client/Root.js
- recipes/react-ssr/client/index.js
- recipes/react-ssr/package-lock.json
- recipes/react-ssr/package.json
- recipes/react-ssr/server/index.js
- recipes/react-ssr/server/main.js
- recipes/react-ssr/webpack.config.js
> docs(recipes): add ssr recipe [fixes #54]

- .gitignore
- lib/routes.js
We have two message types, which contains information about problems when Application building. There are warnings and errors. Currently when error or warning are detected, `webpack-plugin-serve` doesn't replace changed files. This PR allow apply changes to files by HMR if get any warning, because warning it's not critical problem, which affect on build process. Warnings never stopping building process. For example, warning from ESLint (eslint-loader)
> fix(routes): Allow HMR with warnings

- .prettierrc
- index.d.ts
- package-lock.json
- package.json
- test/typescript/usage.test.ts
- tsconfig.json
- tslint.json
Closes #110 
- the index.d.ts is invalid, and causes downstream ts users to be unable to build entirely, the errors cannot be ignored because the declarations are in-repo
- remove `declare module` - this is not needed in-repo - only for out of repo declarations/augmentations
- add ts usage test
- add tooling to test usage
- add needed types dependencies
- hook into `test` script to prevent future errors
None of the above changes change any current tests or runtime code.
If it isn't too much trouble, please release this ASAP since the current `master` breaks any TS build currently.
> Add typescript usage test, fix typescript errors 

- lib/routes.js
Fixes a case in which we tried to send data through a socket that isn't connected due to the client being in the middle of a page reload (and thus closing the connection). This exception killed the whole webpack process.
Example stacktrace:
```
uncaughtException Error: WebSocket is not open: readyState 2 (CLOSING)
at WebSocket.send (/app/node_modules/ws/lib/websocket.js:322:19)
at WebpackPluginServe.socket.progress (/app/node_modules/webpack-plugin-serve/lib/routes.js:87:16)
at WebpackPluginServe.emit (events.js:189:13)
at ProgressPlugin (/app/node_modules/webpack-plugin-serve/lib/index.js:212:16)
at update (/app/node_modules/webpack/lib/ProgressPlugin.js:151:5)
at moduleAdd (/app/node_modules/webpack/lib/ProgressPlugin.js:163:5)
at …
```
> fix: handle a potential uncaughtException

- lib/routes.js
I do not know exactly what is the case in which this issue occurs, however this change should be enough to fix the issue.
Stacktrace:
```
uncaughtException TypeError: filePath.replace is not a function
at WebpackPluginServe.socket.invalid (/project/node_modules/webpack-plugin-serve/lib/routes.js:80:35)
at WebpackPluginServe.emit (events.js:194:15)
at invalid.tap (/project/node_modules/webpack-plugin-serve/lib/index.js:155:41)
at SyncHook.eval (eval at create (/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
at Watchpack.watcher.compiler.watchFileSystem.watch (/project/node_modules/webpack/lib/Watching.js:139:33)
at Object.onceWrapper (events.js:277:13)
at Watchpack.emit …
```
> handle uncaughtException

- recipes/README.md
Point "Static HTML File" link to `static-html-files.md` instead of non-existent `external-html.md`.
> Fix broken "Static HTML File" link

- lib/client/overlays/status.js
Add `background` property to styles for `#wps-status-problems pre`.
Fixes #121
> fix: add `background` property to `#${ns}-problems pre` css rule

- lib/routes.js
Follow up to #113.
Even with the above fix, I encountered a similar issue, this time in the `invalid` handler:
```
uncaughtException Error: WebSocket is not open: readyState 2 (CLOSING)
at WebSocket.send (/app/node_modules/webpack-plugin-serve/node_modules/ws/lib/websocket.js:322:19)
at WebpackPluginServe.socket.invalid (/app/node_modules/webpack-plugin-serve/lib/routes.js:83:16)
at WebpackPluginServe.emit (events.js:189:13)
at invalid.tap (/app/node_modules/webpack-plugin-serve/lib/index.js:155:41)
at SyncHook.eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
at Watchpack.watcher.compiler.watchFileSystem.watch (/app/node_modules/webpack/lib/Watching.js:139:33)
at …
```
> fix: do not send data when socket is not READY

- lib/server.js
There is potential for breakage if users were performing checks to work around this issue, or were expecting the incorrect address in an event hook.
#131 outlines a problem whereby `localhost` is rewritten to `127.0.0.1` after the server has been started and reports the address. That address is used to construct the URI for both console output and the `open` feature. In the referenced issue's case, a whitelist was being used and `127.0.0.1` was not on that list. The mismatch was unexpected.
This commit catches that discrepancy and rewrites the hostname portion of the url data to `localhost`.
> fix: assert localhost when server address doesnt match. fixes #131

- README.md
- recipes/README.md
- recipes/entry-points.md
Fixes #135. The issue was raised that the documentation was not crystal clear on how users should add the `webpack-plugin-serve/client` script to `entry` in a webpack config. The documentation added provides several examples for common `entry` configuration patterns, and links to the documentation in both the root README, and the recipes README.
> docs: add verbose entry point docs

- lib/index.js
- lib/routes.js
- recipes/watch-static-content.md
- [?] bugfix
- [?] feature
This change allows the recipe described here to work: https://github.com/shellscape/webpack-plugin-serve/blob/master/recipes/watch-static-content.md
It basically enables the "reload" event to be emitted so that a reload can manually be triggered.
> Allow event for manually triggering a reload.

- lib/validate.js
- package-lock.json
- package.json
During installation of `webpack-plugin-serve` the following message appears:
>webpack-plugin-serve > joi@14.3.1: This module 
has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
This PR updates `joi@^14.3.0` to `@hapi/joi@^15.1.0`.
> Update 'joi' dependency

- lib/client/overlays/progress-minimal.js
- lib/client/overlays/progress.js
- Fix flash of progress bar on initial page load(https://github.com/shellscape/webpack-plugin-serve/issues/96#issuecomment-457926404)
- Reorder `addCss` and `addHtml` in mini progress bar
I will create another PR for the progress bar disappear timeout issue, because page visibility API has its own problems.
> fix: flash of progress bar on page load

- .github/FEATURES.md
- README.md
- lib/server.js
- package-lock.json
- package.json
- recipes/open-custom-uri.md
The dependency 'opn' is dropped in favor of 'open'.
Users get this warning every time they run `npm install`:
_npm WARN deprecated opn@6.0.0: The package has been renamed to `open`_
> chore: rename package 'opn' to 'open' 

- lib/index.js
This is more of a tertiary fix for #100. It's helpful to the user to know if their defined `publicPath` doesn't match/exist-in any of the static paths defined in the `static` option. That can cause issues and frustration related to #100.
> fix: check that publicPath exists in static paths. fixes #100

- README.md
- docs: add link to proxies recipe in proxying README section (see commit message)
- docs: static should link to koa-static, not itself (see commit message)
I mentioned this in https://github.com/shellscape/webpack-plugin-serve/issues/151#issuecomment-526403200 as well as https://github.com/shellscape/webpack-plugin-serve/pull/158#pullrequestreview-310799087, but those mentions seemed to have been missed 😕  (the `static` section _was_ updated, but the new link pointed to itself, which I also seem to have missed in my review).
I also mentioned in the review that the "Options" section was linked to in the built-in middleware section, but does not contain references to all built-in middleware (like `four0four` or `headers`). I'm still …
> Follow-Up Docs Changes/Fixes to #158

- README.md
`log` is an object that accepts `level` key which is the string
Just a little fix to the README: `log` was declared to be a `String`. Instead it is an object accepting `level` key, which is the actual String here.
> Fix `log` type

- README.md
- lib/index.js
- lib/plugins/ramdisk.js
- lib/validate.js
- package-lock.json
- package.json
- test/fixtures/ramdisk/custom-options.js
- test/ramdisk.test.js
This PR allows you to customize `ramdisk` options by letting the user pass an object containing the options to the `ramdisk` field.
I came by this requirement in a project where the development output doesn't fit the default ramdisk (it's a big build!).
> feat: Allow customizing ramdisk options

- README.md
This fixes #183, documenting the case for using HMR with a HTTP2 dev server.
> chore: Add note to readme about HMR with HTTP2

- lib/routes.js
- package-lock.json
- package.json
- test/fixtures/multi/webpack.config.js
- test/fixtures/ramdisk-empty-pkg/webpack.config.js
- test/fixtures/ramdisk/config-context-error.js
- test/fixtures/ramdisk/config-cwd-error.js
- test/fixtures/ramdisk/custom-options.js
- test/fixtures/ramdisk/webpack.config.js
- test/fixtures/simple/webpack.config.js
- test/helpers/port.js
- test/ramdisk.test.js
- test/wait-for-build.test.js
- test/ws.test.js
> fix: possible circular reference in route

- lib/helpers.js
- lib/plugins/hmr.js
- package.json
- test/helpers.test.js
Since Webpack 5.10 has updated it starts showing an error message:
```shell script
HotModuleReplacementPlugin
The configured output.hotUpdateMainFilename doesn't lead to unique filenames per runtime and HMR update differs between runtimes.
This might lead to incorrect runtime behavior of the applied update.
To fix this, make sure to include [runtime] in the output.hotUpdateMainFilename option, or use the default config.
```
> HotModuleReplacementPlugin webpack's 5.10 error message

- README.md
- lib/client/client.js
- lib/validate.js
- test/validate.test.js
Small, yet important (for me, at least :p) update: enables users of reverse proxies to specify a different protocol scheme for client requests (typically `wss` from the browser) from the protocol scheme served by the server (typically `ws`).
Provides the final, necessary tool to resolve: <https://github.com/shellscape/webpack-plugin-serve/issues/172>.
>  Add `client.protocol` override option for client

- lib/plugins/hmr.js
As per Webpack documentation, [runtime] can be used only for hotUpdateMainFilename and not hotUpdateChunkFilename ( https://webpack.js.org/configuration/output/#outputhotupdatechunkfilename ). By having this template string inside outputhotupdatechunkfilename , the HMR breaks as chunk file names will have an incorrect name and the files won't be found on the server
> Fixed invalid chunkFileName

- package.json
Allow webpack@5 as peerDependency so it don't install version 4 if not needed.
Related to: https://github.com/shellscape/webpack-plugin-serve/issues/216
> feat: Make package compatible with npm@7

- package-lock.json
- package.json
Currently npm 7/8 breaks when trying to install webpack 5 because `webpack-plugin-ramdisk` didn't allow webpack 5 in it's peer dependency range until v2.
This resolves that :)
> fix: update `webpack-plugin-ramdisk` to allow `webpack` 5

- lib/client/overlays/progress-minimal.js
When used with https://github.com/pmmmwh/react-refresh-webpack-plugin this error shows up during incremental builds.
```Cannot read property 'classList' of null```
I've added a check for wrapper and if it's null, it won't try to access `classList`
> make sure wrapper is found before accessing the classList

- lib/routes.js
I'm unsubscribing from this event whenever the socket is closed.
This addresses the Memory Leak warning mentioned in #223
> unregister "unhandled" event when socket is closed
